import assert from "node:assert/strict";
import {extractCaptionCurveInsights} from "./performanceFigureMetadata";
import {visibleCurveKeyPoints} from "./curveInsights";
import {ingest,toFields} from "./ingest";
import {conductivityModule} from "../modules/conductivity";
const caption="Fig. 6. CV analysis in the potential range 0.1–5.0 V vs Na+/Na at fixed scan rate of 1.0 mV/s (1st and 5th cycles). All samples show high currents above 3 V in the first cycle which reduces drastically with further cycling (formation of stable interphases).";
const pts=extractCaptionCurveInsights(caption,"Cyclic voltammogram",7);
assert.equal(pts.length,4);
assert.equal(pts.find(p=>p.field==="cvScanRange")?.value,"0.1–5.0 V");
assert.ok(!pts.some(p=>p.field==="electrochemicalWindow"),"scan limits must never become a stability window");
assert.deepEqual(extractCaptionCurveInsights(caption,"EIS Nyquist",7),[],"CV conditions in a combined caption must not leak into EIS");
const figure={figure:"Fig.3",curveType:"EIS",keyPoints:[{label:"Rct",value:"2.75 Ω cm²",field:"chargeTransferResistance"}]};
const slope={label:"Slope",value:"76 Ω s^-1/2",slope:"76 Ω s^-1/2",source:"figure-annotation" as const,scope:"figure-comparison" as const,interpretation:"A source-supported comparison",evidence:"Printed slope 76",sourcePage:5};
assert.deepEqual(visibleCurveKeyPoints(figure,{label:"B",keyPoints:[slope]}),[slope],"Nyquist values do not appear as readings on a different panel");
const record=ingest({paper:{title:"Test"},cation:"EMIM",anion:"TFSI",performanceFigure:{...figure,keyPoints:[slope]}});
const restored=ingest(toFields(record)).extended.performanceFigure!.keyPoints![0];
assert.equal(restored.interpretation,slope.interpretation);assert.equal(restored.scope,"figure-comparison");assert.equal(restored.evidence,slope.evidence);assert.equal(restored.sourcePage,5);
const csvRow=conductivityModule.csvRow({...record,id:"test",status:"review",createdAt:""});
const exported=JSON.parse(String(csvRow[conductivityModule.csvHeaders.indexOf("performance_figure_json")]));
assert.equal(exported.keyPoints[0].interpretation,slope.interpretation);
assert.equal(exported.keyPoints[0].scope,"figure-comparison");
assert.deepEqual(visibleCurveKeyPoints({...figure,keyPoints:[{...slope,panelLabel:"B"}]},{label:"A"}),[],"panel-specific points are filtered");
console.log("Conductivity curve-insight tests passed");
