import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = readFileSync(resolve(__dirname, 'CandidateReviewSheet.vue'), 'utf-8')

describe('CandidateReviewSheet structure', () => {
  it('saves editable candidate review groups through existing review APIs before approval', () => {
    expect(source).toContain('getCandidateFieldEvidence')
    expect(source).toContain('updateReviewCandidateCofExtracted')
    expect(source).toContain('updateReviewCandidateFields')
    expect(source).toContain('updateReviewCandidateLoadConditions')
    expect(source).toContain('updateReviewCandidateSpeedConditions')
    expect(source).toContain('updateReviewCandidateTribologicalSystem')
    expect(source).toContain('approveReviewCandidate')
    expect(source).toContain('async function saveAndApprove()')
    expect(source).toContain('await updateReviewCandidateCofExtracted(candidateId.value,')
    expect(source).toContain('await updateReviewCandidateFields(candidateId.value, scalarCorrections)')
    expect(source).toContain('await updateReviewCandidateLoadConditions(candidateId.value,')
    expect(source).toContain('await updateReviewCandidateSpeedConditions(candidateId.value,')
    expect(source).toContain('await updateReviewCandidateTribologicalSystem(candidateId.value,')
    expect(source).toContain('await approveReviewCandidate(candidateId.value)')
    expect(source).toContain("'saved-to-database': []")
    expect(source).toContain("emit('saved-to-database')")
    expect(source).not.toContain("'saved-and-approved': []")
    expect(source).not.toContain("emit('saved-and-approved')")
    expect(source).toContain('potential: draft.value.potential || null')
    expect(source).toContain('cation: draft.value.cation || null')
    expect(source).toContain('anion: draft.value.anion || null')
    expect(source).toContain('temperature: draft.value.temperature || null')
  })

  it('presents an evidence-first verify-card layout instead of a flat form + rail', () => {
    expect(source).toContain('Candidate Review')
    expect(source).toContain('const reviewCards: ReviewCardDef[]')
    expect(source).toContain("key: 'ionic_liquid', label: 'Ionic liquid'")
    expect(source).toContain("key: 'cof', label: 'COF'")
    expect(source).toContain("key: 'tribopair', label: 'Tribopair'")
    expect(source).toContain("key: 'conditions', label: 'Conditions'")
    expect(source).toContain('const cardModels = computed')
    expect(source).toContain('v-for="card in cardModels"')
    expect(source).toContain(':data-card="card.key"')
    // status chips drive the "needs attention" signal
    expect(source).toContain("status: 'flagged' | 'confirmed' | 'grounded' | 'check'")
    expect(source).toContain('Needs your attention:')
    // the old form/rail split is gone
    expect(source).not.toContain('Editable review fields')
    expect(source).not.toContain('Evidence rail')
    expect(source).not.toContain('Identity & tribopair correction')
    expect(source).not.toContain('selectedEvidenceFieldKey')
  })

  it('defaults each card to read-only with an inline edit toggle, secondary fields collapsed', () => {
    expect(source).toContain('const editingCards = ref<Set<ReviewCardKey>>')
    expect(source).toContain('function toggleCardEditing(key: ReviewCardKey)')
    expect(source).toContain('function isCardEditing(key: ReviewCardKey)')
    expect(source).toContain('@click="toggleCardEditing(card.key)"')
    expect(source).toContain('v-if="!isCardEditing(card.key)"')
    // missing-value cards auto-open so reviewers land on the gaps
    expect(source).toContain('if (!cardHasValue(card)) autoEdit.add(card.key)')
    // advanced section collapses the secondary fields
    expect(source).toContain('const advancedOpen = ref(false)')
    expect(source).toContain('Advanced details')
    expect(source).toContain('@click="advancedOpen = !advancedOpen"')
  })

  it('couples each card to its strongest evidence inline (quote + source image)', () => {
    expect(source).toContain('function cardBestEvidence')
    expect(source).toContain('function cardEvidenceEntries')
    expect(source).toContain('evidenceEntryQualityScore')
    expect(source).toContain('async function hydrateCardImages()')
    expect(source).toContain('async function hydrateEvidenceImage(entry: FieldEvidenceEntry | null)')
    expect(source).toContain('getPdfFigurePreviews')
    expect(source).toContain('getPdfBboxPreview')
    expect(source).toContain('figurePreviewMatchesEvidence')
    expect(source).toContain('card.imageSrc')
    expect(source).toContain('card.quote')
    expect(source).toContain('@click="openImagePreview(card.imageSrc)"')
    expect(source).toContain('Source image preview')
  })

  it('renders a tight text-region crop for text-grounded values, not the whole figure', () => {
    expect(source).toContain('function evidenceHasTextMatch')
    expect(source).toContain('function entryIsFigureSourced')
    // image selection keys off explicit source_type, not a figure mention in source_label
    expect(source).toContain("['figure', 'visual', 'image', 'table'].includes(sourceType)")
    expect(source).not.toContain('/\\b(?:fig|figure|table|plot)\\.?\\s*\\d*/.test(sourceLabel)')
    // a value with a matched phrase + bbox is cropped tight; figure preview is fallback-only
    expect(source).toContain('const hasTextMatch = evidenceHasTextMatch(entry)')
    expect(source).toContain("const context = hasTextMatch ? 'normal' : 'wide'")
    expect(source).toContain('if (entryIsFigureSourced(entry) && !hasTextMatch)')
  })

  it('highlights the matched phrase inside the quote for at-a-glance judging', () => {
    expect(source).toContain('function highlightQuote(quote: string, matchedText: string)')
    expect(source).toContain('function escapeHtml(value: string)')
    expect(source).toContain('matchedText: evidenceMatchedText(bestEntry)')
    expect(source).toContain('v-html="highlightQuote(card.quote, card.matchedText)"')
    expect(source).toContain('<mark')
  })

  it('lets reviewers confirm or flag each card evidence inline and refreshes from the response', () => {
    expect(source).toContain('confirmCandidateFieldEvidence')
    expect(source).toContain('flagCandidateFieldEvidence')
    expect(source).toContain('unflagCandidateFieldEvidence')
    expect(source).toContain("async function runEvidenceAction(action: 'confirm' | 'flag' | 'unflag', fieldKey: string)")
    expect(source).toContain('evidence.value = response')
    expect(source).toContain('evidenceCache.set(candidateId.value, response)')
    expect(source).toContain("@click=\"runEvidenceAction('confirm', card.actionKey)\"")
    expect(source).toContain("@click=\"runEvidenceAction('flag', card.actionKey)\"")
    expect(source).toContain("@click=\"runEvidenceAction('unflag', card.actionKey)\"")
  })

  it('keeps queue navigation, prefetch, reject, and keyboard shortcuts', () => {
    expect(source).toContain('hasNextCandidate?: boolean')
    expect(source).toContain("'next-candidate': []")
    expect(source).toContain('Next candidate')
    expect(source).toContain('nextRecord?: RecordResponse | null')
    expect(source).toContain('function prefetchNextEvidence')
    expect(source).toContain('prefetchNextEvidence()')
    expect(source).toContain('rejected: []')
    expect(source).toContain('async function rejectCandidate()')
    expect(source).toContain("emit('rejected')")
    expect(source).toContain('@click="rejectCandidate"')
    expect(source).toContain('function handleReviewKeydown')
    expect(source).toContain("window.addEventListener('keydown', handleReviewKeydown)")
    expect(source).toContain("window.removeEventListener('keydown', handleReviewKeydown)")
    expect(source).toContain('Approve')
    expect(source).toContain('Reject')
  })

  it('surfaces readiness and keeps the local blockers guidance', () => {
    expect(source).toContain('readinessLabel')
    expect(source).toContain('canApproveCandidate')
    expect(source).toContain('approvalButtonLabel')
    expect(source).toContain('Ready')
    expect(source).toContain('Needs fix')
    expect(source).toContain('Complete core fields')
    expect(source).toContain("if (canApproveCandidate.value) return 'Save to Database'")
    expect(source).not.toContain("if (canApproveCandidate.value) return 'Approve'")
    expect(source).toContain('Candidate could not be saved to Database.')
    expect(source).not.toContain('Candidate could not be approved.')
    expect(source).toContain('localBlockers')
    expect(source).toContain('coreLayerMissing')
    expect(source).toContain('if (localBlockers.value.length)')
    expect(source).toContain(':disabled="!canApproveCandidate || saving || rejecting"')
    expect(source).toContain('approvalError')
    expect(source).toContain('saveError')
  })

  it('blocks database save only on core flagged evidence, keeping extended/raw flags advisory', () => {
    expect(source).toContain('const CORE_REVIEW_FIELD_KEYS')
    expect(source).toContain("CORE_REVIEW_FIELDS.map((field) => field.key)")
    expect(source).toContain('function flaggedCoreEvidenceKeys')
    expect(source).toContain('CORE_REVIEW_FIELD_KEYS.has(key)')
    expect(source).toContain('const flaggedCore = flaggedCoreEvidenceKeys()')
    expect(source).toContain('if (flaggedCore.length) blockers.push(`Flagged core evidence:')
    expect(source).not.toContain('const flagged = Object.entries(fieldMap.value)\n    .filter(([, entry]) => clean(entry?.review_state).toLowerCase() === \'flagged\')')
    expect(source).not.toContain('Flagged evidence:')
  })

  it('treats structured load and COF min/max values as core-ready, including zero', () => {
    expect(source).toContain('function schemaValuePresent(value: unknown)')
    expect(source).toContain('function firstSchemaValue(...values: unknown[])')
    expect(source).toContain('load.loadMinN ?? load.load_min_N')
    expect(source).toContain('load.loadMaxN ?? load.load_max_N')
    expect(source).toContain('cof.cofMin ?? cof.cof_min')
    expect(source).toContain('cof.cofMax ?? cof.cof_max')
    expect(source).toContain("status: schemaValuePresent(currentValue) ? 'ready'")
    expect(source).toContain("status: schemaValuePresent(value) ? 'ready'")
  })

  it('treats common not-reported placeholders as missing core values', () => {
    expect(source).toContain('const EMPTY_SCHEMA_VALUE_LABELS')
    expect(source).toContain("'not stated'")
    expect(source).toContain("'not reported'")
    expect(source).toContain("'not provided'")
    expect(source).toContain("'not given'")
    expect(source).toContain('!EMPTY_SCHEMA_VALUE_LABELS.has(text)')
    expect(source).not.toContain("!['-', '--', 'n/a', 'na', 'none', 'null', 'unknown', 'review required'].includes(text)")
  })

  it('uses the editable draft, not stale record fallback, for core readiness', () => {
    expect(source).toContain('function schemaFieldValue(key: string)')
    expect(source).not.toContain("if (key === 'cation') return firstSchemaValue(draft.value.cation, record?.cation)")
    expect(source).not.toContain("if (key === 'anion') return firstSchemaValue(draft.value.anion, record?.anion)")
    expect(source).not.toContain("if (key === 'substrate_material') return firstSchemaValue(draft.value.substrateMaterial, record?.substrateMaterial)")
    expect(source).not.toContain("if (key === 'temperature') return firstSchemaValue(draft.value.temperature, record?.temperature)")
  })

  it('surfaces the core / extended / raw schema layers during candidate cleaning', () => {
    expect(source).toContain('type SchemaLayerField')
    expect(source).toContain('const CORE_REVIEW_FIELDS')
    expect(source).toContain('const EXTENDED_REVIEW_FIELDS')
    expect(source).toContain('const schemaLayerSummary = computed')
    expect(source).toContain('function schemaLayerFieldsFromEvidence')
    expect(source).toContain('const currentValue = schemaFieldValue(key)')
    expect(source).toContain("status: schemaValuePresent(currentValue) ? 'ready'")
    expect(source).toContain('function rawFlexibleEntries')
    expect(source).toContain('const RAW_FLEXIBLE_META_KEYS')
    expect(source).toContain("if (key === 'extended_context')")
    expect(source).toContain('!RAW_FLEXIBLE_META_KEYS.has(key)')
    expect(source).toContain('Schema layers')
    expect(source).toContain('Core fields')
    expect(source).toContain('Extended fields')
    expect(source).toContain('Saved raw evidence')
    expect(source).not.toContain('Raw JSON')
    expect(source).toContain('function readableRawFlexibleLabel')
    expect(source).toContain("return key.replace(/_/g, ' ').replace(/\\b\\w/g")
    expect(source).toContain("key: 'additive', label: 'Additive'")
    expect(source).toContain("key: 'test_duration', label: 'Test duration'")
    expect(source).toContain("if (key === 'additive')")
    expect(source).toContain("if (key === 'test_duration')")
    expect(source).toContain('Optional {{ schemaLayerSummary.extendedReady }} captured')
    expect(source).not.toContain("schemaFlexibleValue('additive', 'additive_loading', 'additive_concentration', 'iron_oxide_additive_ratio')")
    expect(source).not.toContain('Extended {{ schemaLayerSummary.extendedReady }}/{{ schemaLayerSummary.extendedFields.length }}')
    expect(source).toContain('Required before approval')
    expect(source).toContain('Optional context')
    expect(source).toContain('Flexible evidence')
    expect(source).toContain('coreLayerMissing')
    expect(source).toContain('v-model="draft.cation"')
    expect(source).toContain('v-model="draft.anion"')
    expect(source).toContain('v-model="draft.temperature"')
  })

  it('lets reviewers clean common extended roughness fields without leaving the sheet', () => {
    expect(source).toContain('surfaceRoughness: string')
    expect(source).toContain('surface_roughness: draft.value.surfaceRoughness || null')
    expect(source).toContain('v-model="draft.surfaceRoughness"')
    expect(source).toContain('v-model="draft.probeRoughness"')
    expect(source).toContain('v-model="draft.substrateRoughness"')
    expect(source).toContain('Surface roughness')
    expect(source).toContain('Probe roughness')
    expect(source).toContain('Substrate roughness')
  })

  it('turns missing core schema fields into a compact clickable fix target', () => {
    expect(source).toContain('missingCoreFields')
    expect(source).toContain('Missing core')
    expect(source).toContain('v-for="field in schemaLayerSummary.missingCoreFields"')
    expect(source).toContain('@click="openMissingCoreCards"')
    expect(source).toContain(':title="`Fix ${field.label}`"')
  })

  it('keeps the candidate review sheet compact, quiet, and evidence-dense', () => {
    expect(source).toContain('max-w-[680px]')
    expect(source).toContain('data-testid="review-evidence-card"')
    expect(source).toContain('grid gap-2')
    expect(source).toContain('text-[1.05rem] font-semibold')
    expect(source).toContain('max-h-36 w-full object-contain')
    expect(source).toContain('h-8 items-center justify-center gap-1.5')
    expect(source).not.toContain('text-2xl font-black')
    expect(source).not.toContain('rounded-xl border bg-white p-4')
    expect(source).not.toContain('max-h-56 w-full object-contain')
  })
})
