import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = readFileSync(resolve(__dirname, 'RecordTable.vue'), 'utf-8')
const workspaceSource = readFileSync(resolve(__dirname, 'IntegratedExplorerWorkspace.vue'), 'utf-8')
const recipeCellSource = readFileSync(resolve(__dirname, 'LubricantRecipeCell.vue'), 'utf-8')
const tribopairCapsuleSource = readFileSync(resolve(__dirname, 'TribopairCapsule.vue'), 'utf-8')
const virtualRowSource = readFileSync(resolve(__dirname, 'VirtualRecordRow.vue'), 'utf-8')
const knowledgePageSource = readFileSync(resolve(__dirname, '../../pages/knowledge/KnowledgePage.vue'), 'utf-8')
const integratedExplorerSource = readFileSync(resolve(__dirname, '../IntegratedExplorer.vue'), 'utf-8')

describe('RecordTable structure thumbnails', () => {
  it('renders public record labels without exposing primary keys in the ID column', () => {
    expect(source).toContain('compactRecordDisplayId(record)')
    expect(source).toContain('>#<')
    expect(source).toContain(':title="recordDisplayId(record)"')
    expect(source).not.toContain('{{ record.id }}')
  })

  it('uses normalized lubricant structure items instead of raw SMILES fields only', () => {
    expect(source).toContain('LubricantRecipeCell')
    expect(recipeCellSource).toContain('lubricantStructureItems')
    expect(recipeCellSource).toContain('MoleculeViewer')
    expect(source).not.toContain('record.cationSmiles || record.anionSmiles')
    expect(source).not.toContain(':smiles="record.cationSmiles"')
    expect(source).not.toContain(':smiles="record.anionSmiles"')
  })

  it('renders ionic liquid recipes through the dedicated compact mixture cell', () => {
    expect(source).toContain('LubricantRecipeCell')
    expect(source).not.toContain('ionicLiquidParts(record.lubricant ||')
    expect(source).not.toContain('formatIonicLiquidPartHtml(part)')
  })

  it('keeps the Database view on the existing row-card style without the merged-IL mode', () => {
    expect(workspaceSource).not.toContain('Merged IL')
    expect(workspaceSource).not.toContain('recordViewMode')
    expect(workspaceSource).not.toContain(':group-by-ionic-liquid')
    expect(source).not.toContain('groupDatabaseRecordsByLiteratureLiquid')
    expect(source).not.toContain('database-il-group-card')
    expect(source).toContain('LubricantRecipeCell')
    expect(source).toContain('TribopairCapsule')
    expect(source).toContain('ConditionMicrobar')
  })

  it('does not show the grey confidence caption under COF in table rows', () => {
    expect(source).not.toContain('Conf:')
    expect(virtualRowSource).not.toContain('Conf:')
    expect(source).not.toContain('confidenceDisplay(confidenceValueFor(record')
    expect(virtualRowSource).not.toContain('confidenceDisplay(confidenceValueFor(record')
  })

  it('opens a preview-style field evidence popover from each data card instead of a separate actions column', () => {
    expect(source).toContain("@click.stop=\"openEvidenceModal(record, 'ionic-liquid', $event)\"")
    expect(source).toContain("@click.stop=\"openEvidenceModal(record, 'conditions', $event)\"")
    expect(source).toContain("@keydown.enter.prevent.stop=\"openEvidenceModal(record, 'cof', $event)\"")
    expect(workspaceSource).toContain('databaseEvidenceField')
    expect(workspaceSource).toContain('database-field-evidence-popover')
    // evidence opens as a centered two-pane modal (no cell-anchored positioning)
    expect(workspaceSource).toContain('@click.self="closeDatabaseEvidencePopover"')
    expect(workspaceSource).toContain('databaseEvidenceFocusedFieldKey')
    expect(workspaceSource).toContain('normalizeDatabaseEvidenceFieldKey')
    expect(workspaceSource).toContain('databaseEvidenceFocusedValue')
    expect(workspaceSource).toContain('splitDatabaseEvidenceQuote')
    expect(workspaceSource).toContain('getRecordFieldEvidence')
    expect(workspaceSource).toContain('getCandidateFieldEvidence')
    expect(workspaceSource).toContain('databaseRecordCacheKey')
    expect(workspaceSource).toContain("databaseRecordEntityType(record) === 'candidate'")
    expect(workspaceSource).toContain('databaseEvidenceFieldKeys')
    expect(workspaceSource).toContain('databaseEvidenceSelectedEntries')
    expect(workspaceSource).toContain('databaseEvidenceTermHits')
    expect(workspaceSource).toContain('getPdfBboxPreview')
    expect(workspaceSource).toContain('databaseEvidenceSlides')
		    expect(workspaceSource).toContain('databaseEvidenceSlideHasContent')
		    expect(workspaceSource).toContain('databaseEvidenceCoveredSemanticKeys')
		    expect(workspaceSource).toContain('isDatabaseVisualEvidenceEntry')
		    expect(workspaceSource).toContain('databaseEvidenceQuoteHighlights')
		    expect(workspaceSource).toContain('databaseEvidenceContextualNumericHighlight')
		    expect(workspaceSource).toContain('databaseEvidenceBestEntriesBySemanticKey')
		    expect(workspaceSource).toContain("openEvidenceModal(record, { syncConfidence: false })")
		    expect(workspaceSource).toContain('setDatabaseEvidencePreferredSlide(record, field)')
		    expect(workspaceSource).toContain('databaseEvidencePreferredSlideIndex')
		    expect(workspaceSource).toContain('databaseEvidenceFocusedFieldKeys')
		    expect(workspaceSource).toContain("probe_material: ['probe_material']")
		    expect(workspaceSource).toContain("substrate_material: ['substrate_material']")
		    expect(workspaceSource).toContain("cation: ['cation']")
		    expect(workspaceSource).toContain("loadvalue: 'load'")
		    expect(workspaceSource).toContain("normal_load: 'load'")
		    expect(workspaceSource).toContain("load_raw: 'load'")
	    expect(workspaceSource).toContain('databaseEvidenceFocusedEntries')
	    expect(workspaceSource).toContain('return []')
	    expect(workspaceSource).toContain("material: ['material', 'material_name']")
	    expect(workspaceSource).toContain("current: ['current']")
	    expect(workspaceSource).toContain("current_density: ['current_density']")
	    expect(workspaceSource).toContain("'current', 'current_density'")
	    expect(workspaceSource).toContain('roleSpecificKeys.has(fieldKey) && databaseEvidenceEntryHasContent(fieldKey, entry)')
		    expect(workspaceSource).toContain('const evidenceOpenToken')
		    expect(workspaceSource).toContain('databaseEvidenceOpenToken')
		    expect(workspaceSource).toContain('isCurrentDatabaseEvidenceRequest(record, field, focusedFieldKey, evidenceOpenToken)')
		    expect(workspaceSource).toContain('if (isCurrentDatabaseEvidenceRequest(record, field, focusedFieldKey, evidenceOpenToken))')
	    expect(workspaceSource).toContain('databaseEvidenceEntryHasPdfLocator')
	    expect(workspaceSource).toContain('databaseEvidenceIsLoading')
	    expect(workspaceSource).toContain('databaseEvidenceDisplayError')
	    expect(workspaceSource).toContain('.filter(({ entry }) => databaseEvidenceEntryHasPdfLocator(entry) && databaseEvidenceShouldRenderPdfPreview(entry))')
	    expect(workspaceSource).toContain('PDF locator available; quote text was not stored for this field.')
	    expect(workspaceSource).toContain('Derived calculation')
	    expect(workspaceSource).toContain('activeDatabaseEvidenceNote')
	    expect(workspaceSource).toContain("'wide'")
	    expect(workspaceSource).not.toContain('|| normalizeDatabaseEvidenceText(entry.value)')
		    expect(workspaceSource).not.toContain('normalizeDatabaseEvidenceText(slide.value)\\n      || normalizeDatabaseEvidenceText(slide.quote?.text)')
    expect(workspaceSource).toContain('Rendering highlighted PDF evidence')
    expect(workspaceSource).toContain('moveDatabaseEvidenceSlide')
    expect(workspaceSource).toContain("if (field === 'ionic-liquid') return ['ionic_liquid'")
    expect(workspaceSource).toContain("if (field === 'cof') return ['cof'")
    expect(workspaceSource).toContain('No field-level quote was stored for this')
    expect(workspaceSource).toContain(":open-evidence-modal=\"handleOpenEvidenceModal\"")
    expect(source).toContain('workspace-card')
    expect(source).toContain('@open-evidence="(fieldKey, event) => openEvidenceModal(record, \'ionic-liquid\', event, fieldKey)"')
    expect(source).toContain('@open-evidence="(fieldKey, event) => openEvidenceModal(record, \'tribopair\', event, fieldKey)"')
    expect(source).toContain('@open-evidence="(fieldKey, event) => openEvidenceModal(record, \'conditions\', event, fieldKey)"')
    expect(source).toContain('aria-label="Open conditions evidence"')
    expect(source).toContain('title="Open field evidence"')
	    expect(workspaceSource).not.toContain(':open-review-record="handleOpenReviewRecord"')
	    expect(workspaceSource).not.toContain('evidenceLoading[evidenceModalRecord.id] || databaseFieldEvidenceLoading[evidenceModalRecord.id]')
	    expect(workspaceSource).not.toContain('databaseFieldEvidenceError[evidenceModalRecord.id] || evidenceError[evidenceModalRecord.id]')
    expect(workspaceSource).not.toContain('Confirm</button>')
    expect(workspaceSource).not.toContain('Flag</button>')
    expect(workspaceSource).not.toContain('Edit</button>')
    expect(workspaceSource).not.toContain('database-field-evidence-drawer')
    expect(source).not.toContain('role="button"')
    expect(source).not.toContain('ACTIONS')
    expect(source).not.toContain('Actions Column')
    expect(source).not.toContain('openEditModal: (record: RecordResponse) => void')
    expect(source).not.toContain('@click="openEditModal(record)"')
    expect(source).not.toContain('@dblclick.stop="openEvidenceModal(record')
    expect(virtualRowSource).toContain('@click.stop="emit(\'openEvidence\', record)"')
    expect(virtualRowSource).not.toContain('@dblclick.stop="emit(\'openEvidence\', record)"')
	    expect(virtualRowSource).not.toContain('Actions Column')
	    expect(virtualRowSource).not.toContain('openEdit:')
	    expect(workspaceSource).toContain('import RecordTable')
	    expect(workspaceSource).not.toContain('import VirtualRecordRow')
	  })

  it('keeps empty database results and duplicate field evidence visually clean', () => {
	    expect(workspaceSource).toContain('<div v-if="result.total > 0" class="flex items-center gap-1">')
	    expect(workspaceSource).toContain('hasRoleSpecificEvidence')
	    expect(workspaceSource).toContain("entries.filter(({ fieldKey }) => !['material', 'material_name'].includes(fieldKey))")
	    expect(workspaceSource).not.toContain("entries.filter(({ fieldKey, entry }) => databaseEvidenceEntryHasContent(fieldKey, entry) || !['material', 'material_name'].includes(fieldKey))")
	    expect(workspaceSource).not.toContain('databaseEvidenceEntryHasPageLocator')
	    expect(workspaceSource).not.toContain('PDF page locator available; quote text and highlight coordinates were not stored for this field.')
	    expect(workspaceSource).toContain('if (!databaseEvidenceEntryHasContent(fieldKey, entry)) continue')
	    expect(workspaceSource).toContain('.filter(({ fieldKey, entry }) => databaseEvidenceEntryHasContent(fieldKey, entry))')
	    expect(workspaceSource).toContain('activeDatabaseEvidenceSlide(evidenceModalRecord)?.noteLabel')
	    // roomy two-pane modal: image pane + scrollable text/context pane shown together
	    expect(workspaceSource).toContain('database-evidence-image-pane')
	    expect(workspaceSource).toContain('database-evidence-content-scroll flex min-h-0 flex-col overflow-y-auto')
	    expect(workspaceSource).toContain("'md:grid-cols-[1.3fr_1fr]'")
	    expect(workspaceSource).toContain('cursor-zoom-in')
	    expect(workspaceSource).toContain('openRecordPdf(evidenceModalRecord, { forcePdf: true })')
	    expect(workspaceSource).not.toContain('database-evidence-image-frame')
	    expect(workspaceSource).not.toContain('max-h-[min(42vh,26rem)]')
	    expect(workspaceSource).toContain('databaseEvidenceSlideDedupeKey')
	    expect(workspaceSource).not.toContain("slide.imageSrc ? 'image' : ''")
	    expect(workspaceSource).toContain('databaseEvidenceShouldRenderPdfPreview')
	    expect(workspaceSource).toContain("if (sourceType === 'text' && normalizeDatabaseEvidenceText(entry.evidence?.quote)) return false")
	    // text-grounded values must not be classified as a figure just because their
	    // source_label cites one, and must prefer the tight crop over the whole figure
	    expect(workspaceSource).toContain('function databaseEntryHasTextMatch(entry: FieldEvidenceEntry)')
	    expect(workspaceSource).not.toContain('/\\b(?:fig|figure|table|plot)\\.?\\s*\\d*/.test(sourceLabel)')
	    expect(workspaceSource).toContain('isDatabaseVisualEvidenceEntry(entry) && !databaseEntryHasTextMatch(entry)')
	    // click-to-open evidence aligns with inline display: source_type only, no label heuristic
	    expect(workspaceSource).not.toContain("source.startsWith('fig')")
	    expect(workspaceSource).not.toContain("source.startsWith('table')")
	    expect(workspaceSource).toContain('databaseEvidenceShouldSuppressBareEvidence')
	    expect(workspaceSource).toContain('isBareMatchedNumber && (!quoteText || isBareQuoteNumber)')
	    expect(workspaceSource).toContain('if ((suppressBareEvidence || !primaryText) && note)')
	    expect(workspaceSource).toContain("databaseEvidenceSemanticKey(slide.fieldKey || '') === 'speed'")
	    expect(workspaceSource).toContain("String(entry.grounding_mode || '').toLowerCase() === 'derived'")
	    expect(workspaceSource).toMatch(/'film_thickness',\s*'substrate_material'/)
	    expect(workspaceSource).not.toContain("'water_content', 'film_thickness']")
	  })

	  it('does not create database evidence slides for fields without an extracted value', () => {
	    expect(workspaceSource).toContain('function databaseEvidenceEntryHasDisplayValue')
	    expect(workspaceSource).toContain('if (!databaseEvidenceEntryHasDisplayValue(entry)) return false')
	    expect(workspaceSource).toContain('if (!databaseEvidenceEntryHasDisplayValue(entry)) continue')
	  })

	  it('does not let focused role-specific tribopair evidence fall back to generic material evidence', () => {
	    expect(workspaceSource).toContain("probe_material: ['probe_material']")
	    expect(workspaceSource).toContain("substrate_material: ['substrate_material']")
	    expect(workspaceSource).toContain("substrate_coating: ['substrate_coating']")
	    expect(workspaceSource).toContain("probe_roughness: ['probe_roughness']")
	    expect(workspaceSource).toContain("substrate_roughness: ['substrate_roughness']")
	    expect(workspaceSource).toContain("cation: ['cation']")
	    expect(workspaceSource).toContain("anion: ['anion']")
	    expect(workspaceSource).not.toContain("probe_material: ['probe_material', 'material', 'material_name']")
	    expect(workspaceSource).not.toContain("substrate_material: ['substrate_material', 'material', 'material_name']")
	    expect(workspaceSource).not.toContain("substrate_coating: ['substrate_coating', 'material', 'material_name']")
	    expect(workspaceSource).not.toContain("probe_roughness: ['probe_roughness', 'surface_roughness']")
	    expect(workspaceSource).not.toContain("substrate_roughness: ['substrate_roughness', 'surface_roughness']")
	    expect(workspaceSource).not.toContain("cation: ['cation', 'ionic_liquid']")
	    expect(workspaceSource).not.toContain("anion: ['anion', 'ionic_liquid']")
	  })

	  it('routes candidate rows into the review sheet without table-level approval controls', () => {
	    expect(source).toContain('isCandidateRecord(record)')
	    expect(source).toContain('record.reviewEntityType || record.entityType')
	    expect(source).toContain('Review candidates before batch deletion')
	    expect(source).toContain('reviewCandidateRecord?: (record: RecordResponse) => void')
	    expect(source).toContain('Review candidate')
	    expect(source).toContain('reviewCandidateRecord?.(record)')
	    expect(source).not.toContain('candidateEvidenceQualityShortLabel(record)')
	    expect(source).not.toContain('candidateEvidenceQualityLabel(candidateEvidenceQuality(record))')
	    expect(source).not.toContain('candidateEvidenceQualityBadgeClass(record)')
	    expect(source).not.toContain('Located')
	    expect(source).not.toContain('Page-only')
	    expect(source).toContain('.filter((record) => !isCandidateRecord(record))')
	    expect(source).not.toContain('Candidate row, not yet promoted to library record')
	    expect(source).not.toContain('approveCandidateRecord?: (record: RecordResponse) => void')
	    expect(source).not.toContain('approveCandidateRecord?.(record)')
	    expect(source).not.toContain('approvingCandidateId')
	    expect(source).not.toContain('Approve candidate')
	    expect(workspaceSource).toContain("databaseRecordEntityType(record) !== 'candidate'")
	    expect(workspaceSource).toContain('CandidateReviewSheet')
	    expect(workspaceSource).toContain('const reviewSheetRecord = ref<RecordResponse | null>(null)')
	    expect(workspaceSource).toContain('function openCandidateReviewSheet(record: RecordResponse)')
	    expect(workspaceSource).toContain(':review-candidate-record="openCandidateReviewSheet"')
	    expect(workspaceSource).toContain('@saved-and-approved="handleCandidateReviewApproved"')
	    // Per-row inline approval was abandoned; approval flows through the review sheet
	    // (single) or the bulk toolbar (many), never a per-row approve button/state.
	    expect(workspaceSource).not.toContain('reviewActionPendingId')
	    expect(workspaceSource).not.toContain('reviewActionError')
	    expect(workspaceSource).not.toContain('async function handleApproveCandidateRecord(record: RecordResponse)')
	    expect(workspaceSource).not.toContain(':approving-candidate-id')
	    expect(workspaceSource).not.toContain(':approve-candidate-record')
	  })

  it('keeps evidence quality labels out of database and review table rows', () => {
	    expect(source).not.toContain('recordEvidenceGrade(record)')
	    expect(source).not.toContain('recordEvidenceGradeLabel(record)')
	    expect(source).not.toContain('recordEvidenceGradeBadgeClass(record)')
	    expect(source).not.toContain('Strong evidence')
	    expect(source).not.toContain('Weak evidence')
	    expect(source).not.toContain("v-else-if=\"recordEvidenceGrade(record)\"")
	    expect(source).not.toContain('candidateEvidenceQualityShortLabel(record)')
	  })

	  it('threads focusRecordId from knowledge entry points to a highlighted virtual row', () => {
	    expect(knowledgePageSource).toContain('focusRecordId?: number | null')
	    expect(knowledgePageSource).toContain("'clear-focused-record': []")
	    expect(knowledgePageSource).toContain(':focus-record-id="focusRecordId"')
	    expect(knowledgePageSource).toContain("@clear-focused-record=\"emit('clear-focused-record')\"")
	    expect(integratedExplorerSource).toContain('focusRecordId?: number | null')
	    expect(integratedExplorerSource).toContain("'clear-focused-record': []")
	    expect(integratedExplorerSource).toContain(':focus-record-id="focusRecordId"')
	    expect(integratedExplorerSource).toContain("@clear-focused-record=\"$emit('clear-focused-record')\"")
	    expect(workspaceSource).toContain(':focus-record-id="focusRecordId ?? null"')
	    expect(workspaceSource).toContain("targetRecordId: toRef(props, 'focusRecordId')")
	    expect(workspaceSource).toContain("targetEntityType: toRef(props, 'focusEntityType')")
	    expect(workspaceSource).toContain('immediate: true')
	    expect(workspaceSource).toContain('focusHopsRemaining.value = 12')
	    expect(workspaceSource).toContain('goToPage(currentPage.value + 1)')
	    expect(source).toContain('focusRecordId?: number | null')
	    expect(source).toContain('focusEntityType?:')
	    expect(source).toContain('rowNumberStart?: number')
	    expect(source).toContain('recordEntityType(record)')
	    expect(source).toContain('isFocusedRecord(record)')
	    expect(source).toContain('virtualizer.value.scrollToIndex(focusedIndex)')
	    expect(source).toContain('pageScrollKey')
	    expect(source).toContain('virtualizer.value.scrollToOffset(0)')
	    expect(source).toContain('database-focus-record')
	    expect(source).toContain(':aria-current="isFocusedRecord(record) ? \'true\' : undefined"')
	  })

  it('makes macro tribopairs readable as an animated contact rig', () => {
    expect(tribopairCapsuleSource).toContain('macro-rig')
    expect(tribopairCapsuleSource).toContain('macro-rig__counterface')
    expect(tribopairCapsuleSource).toContain('macro-rig__specimen')
    expect(tribopairCapsuleSource).toContain('macro-rig__motion')
    expect(tribopairCapsuleSource).toContain('@keyframes macro-contact')
    expect(tribopairCapsuleSource).toContain('prefers-reduced-motion')
    expect(tribopairCapsuleSource).toContain('MACRO')
    expect(tribopairCapsuleSource).not.toContain(':global(.dark)')
  })

  it('makes nano tribopairs feel like a live probe over a substrate', () => {
    expect(tribopairCapsuleSource).toContain('nano-rig')
    expect(tribopairCapsuleSource).toContain('nano-rig__probe')
    expect(tribopairCapsuleSource).toContain('nano-rig__field')
    expect(tribopairCapsuleSource).toContain('nano-rig__scanline')
    expect(tribopairCapsuleSource).toContain('nano-rig__substrate')
    expect(tribopairCapsuleSource).toContain('@keyframes nano-probe-hover')
    expect(tribopairCapsuleSource).toContain('@keyframes nano-scan')
    expect(tribopairCapsuleSource).toContain('NANO')
    expect(tribopairCapsuleSource).toContain('prefers-reduced-motion')
    expect(tribopairCapsuleSource).not.toContain('nano-rig__cantilever')
  })

  it('keeps header column widths aligned with body column widths', () => {
    expect(source).toContain('const COL_SELECT = \'w-[48px]\'')
    expect(source).toContain('const COL_ID = \'w-[56px]\'')
    expect(source).toContain('const COL_IONIC = \'w-[280px]\'')
    expect(source).toContain('const COL_TRIBOPAIR = \'w-[240px]\'')
    expect(source).toContain('const COL_CONDITIONS = \'w-[304px]\'')
    expect(source).toContain('const COL_COF = \'w-[126px]\'')
    expect(source).toContain('const COL_LITERATURE = \'w-[210px]\'')
    expect(source).toContain(':class="COL_TRIBOPAIR"')
    expect(source).toContain(':class="COL_CONDITIONS"')
    expect(source).toContain('overflow-x-auto overflow-y-hidden')
    expect(source).toContain('min-w-[1264px]')
    expect(source).toContain('overflow-y-auto overflow-x-hidden')
  })

  it('lets the record table fit the available database pane height', () => {
    expect(source).toContain('database-record-table flex min-h-0 flex-1 flex-col')
    expect(source).toContain('class="virtual-table-body min-w-[1264px] flex-1 overflow-y-auto overflow-x-hidden"')
    expect(source).not.toContain('height: calc(100vh - 420px)')
    expect(source).not.toContain('max-height: 600px')
  })

  it('routes the Literature button through the app-level Source Grounding workspace', () => {
    expect(workspaceSource).toContain("emit('view-literature', {")
    expect(workspaceSource).toContain("mode: 'grounding'")
    expect(workspaceSource).toContain('recordId: databaseRecordEntityId(record)')
    expect(workspaceSource).toContain('if (!record.literatureId) {')
    expect(workspaceSource).toContain('openRecordPdf(record, { forcePdf: true })')
  })

  it('uses pointer affordance for editable cards and a compact ruler-style table header', () => {
    expect(source).toContain('workspace-card')
    expect(source).toContain('cursor-pointer')
    expect(source).toContain('column-ruler-label')
    expect(source).toContain('column-ruler-mark')
    expect(source).toContain('max-w-[296px]')
    expect(source).toContain('justify-center')
    expect(source).not.toContain('justify-end px-3 py-3')
    expect(source).not.toContain('table-head-label')
    expect(virtualRowSource).toContain('workspace-card')
    expect(virtualRowSource).toContain('cursor-pointer')
  })

  it('uses a compact ion-pair signature so cations and anions are legible without stacked thumbnails', () => {
    expect(recipeCellSource).toContain('ion-pair-signature')
    expect(recipeCellSource).toContain('ion-role-rail')
    expect(recipeCellSource).toContain('ion-pair-lines')
    expect(recipeCellSource).toContain('cationDisplay')
    expect(recipeCellSource).toContain('anionDisplay')
    expect(recipeCellSource).toContain('ion-structure-spread')
    expect(recipeCellSource).toContain('ion-structure-card--cation')
    expect(recipeCellSource).toContain('ion-structure-card--anion')
    expect(recipeCellSource).toContain('C+')
    expect(recipeCellSource).toContain('A-')
    expect(recipeCellSource).toContain('recipe-ratio-chip')
    expect(recipeCellSource).not.toContain('recipe-thumb-stack')
    expect(recipeCellSource).not.toContain('recipe-ion-stack')
  })

  it('lets reviewers bulk-select candidates without colliding with record delete selection', () => {
    expect(source).toContain('reviewQueueMode?: boolean')
    expect(source).toContain('selectedCandidateIds?: Set<string>')
    expect(source).toContain("'toggle-select-candidate': [entityId: string]")
    expect(source).toContain("'toggle-select-all-candidates': [select: boolean]")
    expect(source).toContain('function candidateKey(record: RecordResponse)')
    expect(source).toContain('const allCandidatesSelected = computed')
    expect(source).toContain('v-if="reviewQueueMode && isCandidateRecord(record)"')
    expect(source).toContain("emit('toggle-select-candidate', candidateKey(record))")
  })

  it('wires the workspace bulk review toolbar to the per-candidate review endpoints', () => {
    expect(workspaceSource).toContain('const selectedCandidateIds = ref<Set<string>>')
    expect(workspaceSource).toContain('function handleBulkApproveCandidates')
    expect(workspaceSource).toContain('function handleBulkRejectCandidates')
    expect(workspaceSource).toContain('approveReviewCandidate')
    expect(workspaceSource).toContain('rejectReviewCandidate')
    expect(workspaceSource).toContain('@click="handleBulkApproveCandidates"')
    expect(workspaceSource).toContain('@click="handleBulkRejectCandidates"')
    expect(workspaceSource).toContain(':review-queue-mode="isReviewQueue"')
    expect(workspaceSource).toContain(':selected-candidate-ids="selectedCandidateIds"')
  })

  it('supports a compact density mode wired from the workspace toolbar to the cells', () => {
    // RecordTable exposes density + drives a shorter virtual row in compact mode.
    expect(source).toContain("density?: 'comfortable' | 'compact'")
    expect(source).toContain('const COMPACT_ROW_HEIGHT')
    expect(source).toContain('rowHeight.value')
    expect(source).toContain(':compact="isCompact"')
    // Compact mode drops the molecular-structure SVG spread (the main height driver).
    expect(recipeCellSource).toContain('visibleStructureCards.length && !compact')
    // Workspace persists the choice and passes it down.
    expect(workspaceSource).toContain('function setTableDensity')
    expect(workspaceSource).toContain("localStorage.setItem(TABLE_DENSITY_KEY")
    expect(workspaceSource).toContain(':density="tableDensity"')
  })

  it('groups records under paper headers, disabled while a column sort is active', () => {
    // RecordTable builds a header|record display stream and renders header rows.
    expect(source).toContain('groupByPaper?: boolean')
    expect(source).toContain('const displayRows = computed')
    expect(source).toContain("kind: 'header'")
    expect(source).toContain('virtual-group-header')
    expect(source).toContain('visibleDisplayRows')
    // Workspace owns the toggle and forces it off when sorting.
    expect(workspaceSource).toContain('const effectiveGroupByPaper = computed')
    expect(workspaceSource).toContain('!groupingDisabledBySort.value')
    expect(workspaceSource).toContain(':group-by-paper="effectiveGroupByPaper"')
    expect(workspaceSource).toContain('@click="setGroupByPaper(!tableGroupByPaper)"')
  })

  it('renders the Review Queue as a master-detail paper rail scoped via literatureId', () => {
    // Whole-queue backlog drives the rail; selecting a paper scopes the query.
    expect(workspaceSource).toContain('getReviewBacklog')
    expect(workspaceSource).toContain('const selectedReviewLiteratureId = ref<number | null>')
    expect(workspaceSource).toContain('const selectedReviewLiteratureIds = ref<number[]>')
    expect(workspaceSource).toContain("selectedReviewLiteratureIds.value.join(',')")
    expect(workspaceSource).toContain('function selectReviewPaper')
    expect(workspaceSource).toContain('reviewLiteratureId: selectedReviewLiteratureFileId')
    expect(workspaceSource).toContain('Sources in review queue')
    expect(workspaceSource).toContain('@click="selectReviewPaper(paper.literatureId)"')
    // The composable scopes candidates to one paper through the file_id filter.
    const composableSource = readFileSync(resolve(__dirname, '../../composables/useRecordSearch.ts'), 'utf-8')
    expect(composableSource).toContain('reviewLiteratureId')
  })

  it('offers a scoped re-extract action for the selected review paper', () => {
    expect(workspaceSource).toContain('review-reextract-button')
    expect(workspaceSource).toContain('reviewReextractConfirmOpen')
    expect(workspaceSource).toContain('review-reextract-progressbar')
    expect(workspaceSource).toContain('reviewReextractProgress')
    expect(workspaceSource).toContain('getLatestExtractionRun')
    expect(workspaceSource).toContain('async function confirmReviewReextract')
    expect(workspaceSource).toContain("await extractData(String(literatureId), true, 'auto', undefined, 'tribology')")
    expect(workspaceSource).toContain('await waitForReviewReextractRun(literatureId)')
    expect(workspaceSource).toContain("getLatestExtractionRun(literatureId, 'tribology')")
    expect(workspaceSource).toContain('await loadReviewBacklog()')
    expect(workspaceSource).toContain('await fetchData()')
  })
})
