import assert from "node:assert/strict";
import React, { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { TeachingGateway } from "./TeachingGateway";
(globalThis as typeof globalThis & { React: typeof React }).React = React;
const html = renderToStaticMarkup(createElement(TeachingGateway));
assert.equal((html.match(/<button/g) ?? []).length, 4);
assert.doesNotMatch(html, /<input|<form/);
for (const groupNo of [1, 2, 3, 4]) assert.match(html, new RegExp(`Group ${groupNo}`));
assert.match(html, /Round 2/); assert.match(html, /Paper 4/);
assert.match(html, /href="\/teaching\/admin"/);
assert.match(html, /lang="en-US"/);
assert.match(html, />Data extraction</);
assert.equal((html.match(/bg-brand-50/g) ?? []).length, 4);
assert.equal((html.match(/bg-violet-50/g) ?? []).length, 4);
const embedded = renderToStaticMarkup(createElement(TeachingGateway, { embedded: true }));
assert.doesNotMatch(embedded, /<h1/);
assert.equal((embedded.match(/<button/g) ?? []).length, 4);
const teacher = renderToStaticMarkup(createElement(TeachingGateway, { initialMode: "teacher" }));
assert.match(teacher, /Opening instructor dashboard/);
assert.doesNotMatch(teacher, /<input|<form/);
console.log("Simple teaching entry component tests passed");
