import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = readFileSync(resolve(__dirname, 'HomePage.vue'), 'utf8')

describe('HomePage research agent shell', () => {
  it('matches the Elicit-style home entry points', () => {
    expect(source).toContain('canAccessAdmin: boolean')
    expect(source).toContain("activeModeLabel = ref('Extraction workflow')")
    expect(source).toContain('modeMenuOpen')
    expect(source).toContain('modeMenuSections')
    expect(source).toContain('WORKFLOWS')
    expect(source).toContain('TOOLS')
    expect(source).toContain('Extraction workflow')
    expect(source).toContain('Research agent')
    expect(source).toContain('Report')
    expect(source).toContain('Systematic review')
    expect(source).toContain('Extract data')
    expect(source).toContain('Database')
    expect(source.indexOf("label: 'Extract data'")).toBeLessThan(source.indexOf("label: 'Find papers'"))
    expect(source.indexOf("label: 'Database'")).toBeLessThan(source.indexOf("label: 'Chat with papers'"))
    expect(source).toContain("target: 'database'")
    expect(source).toContain('PRO')
    expect(source).toContain('Open Database')
    expect(source).not.toContain('Create table')
    expect(source).toContain('Review evidence')
    expect(source).toContain('Upload papers')
  })

  it('unlocks pro modes for admin users', () => {
    expect(source).toContain('isModeItemLocked')
    expect(source).toContain('item.locked && !props.canAccessAdmin')
    expect(source).toContain('if (isModeItemLocked(item)) return')
    expect(source).toContain('v-if="isModeItemLocked(item)"')
  })

  it('puts Extract Data and Database in the first-screen primary workflow', () => {
    expect(source).toContain('const primaryWorkflowActions')
    expect(source).toContain('const extractionCommandMetrics')
    expect(source).toContain('Extraction workbench')
    expect(source).toContain('Database workspace')
    expect(source).toContain('Review evidence')
    expect(source).toContain('Active runs')
    expect(source).toContain('Structured records')
    expect(source).toContain('Evidence checks')
    expect(source).toContain('summary.value.today.runningRuns')
    expect(source).toContain('summary.value.health.datasetReadyRecords')
    expect(source).toContain("target: 'upload-pdfs'")
    expect(source).toContain("target: 'database'")
    expect(source).toContain("label: 'Extraction workflow', icon: BookOpen, target: 'upload-pdfs', locked: false")
    expect(source).toContain("label: 'Extract data', icon: BookOpen, target: 'upload-pdfs', locked: false")
    expect(source).toContain('placeholder="Upload a paper, extract friction records, or open the database..."')
    expect(source).toContain('aria-label="Run extraction workflow"')
    expect(source).toContain("@click=\"emitRoute('Upload papers', 'upload-pdfs')\"")
    expect(source).toContain('v-for="action in primaryWorkflowActions"')
    expect(source.indexOf('v-for="action in primaryWorkflowActions"')).toBeLessThan(source.indexOf('<textarea'))
    expect(source).toContain('min-h-[7rem]')
    expect(source).toContain('rows="3"')
    expect(source).toContain('border-[#39546a] bg-[#39546a] text-white')
    expect(source).toContain('justify-start')
    expect(source).not.toContain('Generate slides')
    expect(source).not.toContain('Draft report')
    expect(source).not.toContain('Map landscape')
  })

  it('keeps the page focused instead of showing the old dashboard modules', () => {
    expect(source).not.toContain('HomeLiteratureChat')
    expect(source).not.toContain('HomeHealthSnapshot')
    expect(source).not.toContain('AI-POWERED LITERARY RESEARCH ASSISTANT')
    expect(source).not.toContain('/ioniclink.png')
    expect(source).not.toContain('topNavItems')
    expect(source).not.toContain('Home navigation')
  })
})
