import assert from "node:assert/strict";
import { createDemoState, demoReducer, restoreFeedback, usersCsv } from "./demo";

const initial = createDemoState();
let current = initial;
for (let i = 0; i < 20; i++) current = demoReducer(current, {type: "tick"});
assert.equal(current.tick, 20);
assert.equal(current.moduleCounts.reduce((a, b) => a + b, 0), 112);
assert.equal(current.successful, 108);
assert.equal(current.users.reduce((sum, user) => sum + user.operations, 0) - initial.users.reduce((sum, user) => sum + user.operations, 0), 20);
assert.equal(current.events.length, 5);
assert.equal(current.events[0].id, "live-20");
assert.equal(initial.tick, 0, "ticks preserve the initial seed state");
const replied = demoReducer(current, {type: "reply", id: "F-001", reply: " 已记录这个建议。 "});
assert.equal(replied.feedback.filter(item => !item.reply).length, 2);
assert.equal(replied.feedback[0].reply, "已记录这个建议。");
const saved = JSON.stringify({version: 1, replies: [{id: "F-001", reply: "已记录这个建议。"}, {id: "F-002", reply: 123}, {id: "unknown", reply: "irrelevant"}]});
assert.equal(restoreFeedback(saved)[0].reply, "已记录这个建议。");
assert.equal(restoreFeedback(saved)[1].reply, "");
assert.deepEqual(restoreFeedback("invalid-json"), initial.feedback);
assert.deepEqual(restoreFeedback('{"version":2,"replies":[]}'), initial.feedback);
assert.deepEqual(demoReducer(replied, {type: "reset"}), initial);
const csv = usersCsv(initial.users.slice(0, 2), "今天");
assert.ok(csv.startsWith("\uFEFF"));
assert.equal(csv.split("\r\n").length, 3);
assert.match(csv, /前端演示数据/);
assert.match(csv, /用户 002/);
assert.doesNotMatch(csv, /用户 003/);
console.log("Usage demo updates, bounded events, feedback persistence and filtered export passed");
