import assert from "node:assert/strict";
import { createSimpleExperiment, joinSimpleExperiment, getSimpleStudent, startSimpleExtraction,
  failSimpleExtraction, finishSimpleExtraction, submitSimpleStudent, saveSimpleDraft, reviewSimpleStudent, getSimpleDashboard,
  attachSimpleStudentPaper, setSimpleStudentGold, getSimpleTask, setSimpleTaskGold } from "./simpleStore";
import { closeTeachingStoreForTests, getTeachingDb } from "./store";
import type { SimpleRow } from "./simpleShared";
const gold: SimpleRow[] = [{ cation: "EMIM", anion: "BF4", substrate: "steel", temperature: "25", load: "1", cof: "0.1" }];
const exp = createSimpleExperiment({ name: "Comparison", sourceId: "source", paperTitle: "Paper", gold });
const ai = joinSimpleExperiment(exp.aiInviteCode, "Alice").participantId;
assert.throws(() => joinSimpleExperiment(exp.manualInviteCode, "Ａｌｉｃｅ"), /already joined/);
assert.equal(getSimpleStudent(ai).mode, "ai");
assert.equal(JSON.stringify(getSimpleStudent(ai)).includes('"gold"'), false);
assert.throws(() => submitSimpleStudent(ai, { version: 0, rows: gold }), /Complete extraction/);
let state = startSimpleExtraction(ai, 0);
const started = state.startedAt;
assert.throws(() => startSimpleExtraction(ai, 0), /Refresh/);
state = failSimpleExtraction(ai, state.version, "temporary");
state = startSimpleExtraction(ai, state.version);
assert.equal(state.startedAt, started);
assert.throws(() => startSimpleExtraction(ai, state.version), /6 minutes/);
const staleVersion = state.version;
const staleRow = getSimpleDashboard(exp.id).students[0];
staleRow.extractionAttemptAt = new Date(Date.now() - 361_000).toISOString();
getTeachingDb().prepare("UPDATE simple_students SET payload = ? WHERE id = ?").run(JSON.stringify(staleRow), ai);
state = startSimpleExtraction(ai, staleVersion);
assert.equal(state.startedAt, started);
assert.throws(() => finishSimpleExtraction(ai, staleVersion, gold), /Refresh/);
assert.throws(() => submitSimpleStudent(ai, { version: state.version, rows: gold }), /Complete extraction/);
state = finishSimpleExtraction(ai, state.version, gold);
state = submitSimpleStudent(ai, { version: state.version, rows: gold, manualSeconds: 900 });
assert.equal(state.result!.accuracy, 1);
assert.notEqual(state.elapsedSeconds, 900);
assert.throws(() => saveSimpleDraft(ai, { version: state.version, rows: gold }), /state/);
let teacher = getSimpleDashboard(exp.id).students[0];
reviewSimpleStudent(ai, { version: teacher.version, overrides: { [teacher.score!.cells[0].key]: false } });
teacher = getSimpleDashboard(exp.id).students[0];
assert.equal(teacher.score!.machineAccuracy, 1);
assert.equal(teacher.score!.accuracy, 5 / 6);
assert.throws(() => reviewSimpleStudent(ai, { version: teacher.version, overrides: { bad: true } }), /field/);
const manual = joinSimpleExperiment(exp.manualInviteCode, "Bob").participantId;
const credential = getSimpleStudent(manual).resumeCode;
assert.ok(credential.length >= 12);
assert.throws(() => joinSimpleExperiment(exp.manualInviteCode, "Bob", "bad"), /recovery code/);
assert.throws(() => joinSimpleExperiment(exp.aiInviteCode, "Bob", credential), /group/);
assert.throws(() => joinSimpleExperiment(exp.manualInviteCode, "Bob", 123 as unknown as string), /Invalid/);
assert.throws(() => startSimpleExtraction(manual, 0), /state/);
assert.throws(() => submitSimpleStudent(manual, { version: 0, rows: gold, manualSeconds: -1 }), /time/);
saveSimpleDraft(manual, { version: 0, rows: gold });
assert.equal(joinSimpleExperiment(exp.manualInviteCode, "Bob", credential).participantId, manual);
assert.deepEqual(getSimpleStudent(manual).rows, gold);
assert.equal(getSimpleStudent(manual).version, 1);
assert.equal(submitSimpleStudent(manual, { version: 1, rows: gold, manualSeconds: 120 }).elapsedSeconds, 120);
const ownExp = createSimpleExperiment({ name: "Student papers" });
assert.equal(ownExp.sourceId, "");
assert.deepEqual(ownExp.gold, []);
const ownManual = joinSimpleExperiment(ownExp.manualInviteCode, "Student 1").participantId;
const ownAi = joinSimpleExperiment(ownExp.aiInviteCode, "Student 2").participantId;
assert.throws(() => startSimpleExtraction(ownAi, 0), /Upload/);
assert.throws(() => submitSimpleStudent(ownManual, { version: 0, rows: gold, manualSeconds: 60 }), /Upload/);
const paperId = "11111111-1111-1111-1111-111111111111";
let ownState = attachSimpleStudentPaper(ownManual, { version: 0, sourceId: paperId, paperTitle: "Own paper" });
assert.equal(ownState.experiment.sourceId, paperId);
assert.equal(getSimpleStudent(ownAi).experiment.sourceId, "");
assert.throws(() => attachSimpleStudentPaper(ownManual, { version: 0, sourceId: paperId, paperTitle: "Stale" }), /Refresh/);
ownState = submitSimpleStudent(ownManual, { version: ownState.version, rows: gold, manualSeconds: 60 });
assert.equal(ownState.result, null);
assert.equal(ownState.pendingGrade, true);
assert.equal(ownState.elapsedSeconds, 60);
assert.throws(() => attachSimpleStudentPaper(ownManual, { version: ownState.version, sourceId: paperId, paperTitle: "Locked" }), /state/);
ownState = setSimpleStudentGold(ownManual, { version: ownState.version, gold });
assert.equal(ownState.result?.accuracy, 1);
assert.equal(ownState.pendingGrade, false);
assert.equal(JSON.stringify(ownState).includes('"gold"'), false);
let ownTeacher = getSimpleDashboard(ownExp.id).students.find(s => s.id === ownManual)!;
assert.deepEqual(ownTeacher.paper?.gold, gold);
ownState = reviewSimpleStudent(ownManual, { version: ownState.version, overrides: { [ownTeacher.score!.cells[0].key]: false } });
assert.equal(ownState.result?.accuracy, 5 / 6);
ownState = setSimpleStudentGold(ownManual, { version: ownState.version, gold: [{ ...gold[0], cation: "Different" }] });
ownTeacher = getSimpleDashboard(ownExp.id).students.find(s => s.id === ownManual)!;
assert.deepEqual(ownTeacher.overrides, {});
assert.equal(ownState.result?.machineAccuracy, 5 / 6);
assert.equal(ownTeacher.reviewedAt, null);
let ownAiState = attachSimpleStudentPaper(ownAi, { version: 0, sourceId: paperId, paperTitle: "AI paper" });
ownAiState = startSimpleExtraction(ownAi, ownAiState.version);
const runningVersion = ownAiState.version;
setSimpleStudentGold(ownAi, { version: runningVersion, gold });
assert.equal(getSimpleStudent(ownAi).version, runningVersion);
assert.throws(() => attachSimpleStudentPaper(ownAi, { version: ownAiState.version, sourceId: paperId, paperTitle: "Locked" }), /state/);
ownAiState = finishSimpleExtraction(ownAi, ownAiState.version, gold);
ownAiState = attachSimpleStudentPaper(ownAi, { version: ownAiState.version, sourceId: paperId, paperTitle: "Replacement" });
assert.equal(ownAiState.status, "idle");
assert.equal(ownAiState.startedAt, null);
assert.equal(ownAiState.extractedAt, null);
assert.deepEqual(ownAiState.rows, []);
// Same content, different upload IDs and filenames, shares one answer key.
const taskExp = createSimpleExperiment({ name: "Shared paper tasks" });
const taskAiId = joinSimpleExperiment(taskExp.aiInviteCode, "AI").participantId;
const taskManualId = joinSimpleExperiment(taskExp.manualInviteCode, "Manual").participantId;
let taskAi = attachSimpleStudentPaper(taskAiId, { version: 0, sourceId: paperId, paperTitle: "a.pdf", fingerprint: "same-content" });
let taskManual = attachSimpleStudentPaper(taskManualId, { version: 0, sourceId: "22222222-2222-2222-2222-222222222222", paperTitle: "renamed.pdf", fingerprint: "same-content" });
assert.equal(taskAi.taskId, taskManual.taskId);
assert.equal(getSimpleDashboard(taskExp.id).tasks.length, 1);
assert.equal(JSON.stringify(taskAi.task).includes("gold"), false);
taskAi = startSimpleExtraction(taskAiId, taskAi.version);
taskManual = submitSimpleStudent(taskManualId, { version: taskManual.version, rows: gold, manualSeconds: 90 });
const task = getSimpleTask(taskAi.taskId!);
setSimpleTaskGold(task.id, { version: task.version, gold });
assert.equal(getSimpleStudent(taskAiId).version, taskAi.version);
assert.equal(getSimpleStudent(taskManualId).result?.accuracy, 1);
assert.equal(getSimpleStudent(taskManualId).version, taskManual.version + 1);
assert.throws(() => setSimpleTaskGold(task.id, { version: task.version, gold }), /Refresh/);
taskAi = finishSimpleExtraction(taskAiId, taskAi.version, gold);
taskAi = submitSimpleStudent(taskAiId, { version: taskAi.version, rows: gold });
assert.equal(taskAi.result?.accuracy, 1);
const sharedTeacher = getSimpleDashboard(taskExp.id).students.find(value => value.id === taskAiId)!;
reviewSimpleStudent(taskAiId, { version: taskAi.version, overrides: { [sharedTeacher.score!.cells[0].key]: false } });
setSimpleTaskGold(task.id, { version: getSimpleTask(task.id).version, gold });
assert.equal(getSimpleStudent(taskAiId).result?.accuracy, 1);
assert.deepEqual(getSimpleDashboard(taskExp.id).students.find(value => value.id === taskAiId)!.overrides, {});
const lateId = joinSimpleExperiment(taskExp.manualInviteCode, "Late").participantId;
const late = attachSimpleStudentPaper(lateId, { version: 0, sourceId: paperId, paperTitle: "another-name.pdf", fingerprint: "same-content" });
assert.equal(submitSimpleStudent(lateId, { version: late.version, rows: gold, manualSeconds: 30 }).result?.accuracy, 1);
const distinctId = joinSimpleExperiment(taskExp.manualInviteCode, "Different").participantId;
const distinct = attachSimpleStudentPaper(distinctId, { version: 0, sourceId: paperId, paperTitle: "a.pdf", fingerprint: "different-content" });
assert.notEqual(distinct.taskId, task.id);
const anotherExp = createSimpleExperiment({ name: "Other experiment" });
const anotherId = joinSimpleExperiment(anotherExp.manualInviteCode, "Other").participantId;
assert.notEqual(attachSimpleStudentPaper(anotherId, { version: 0, sourceId: paperId, paperTitle: "a.pdf", fingerprint: "same-content" }).taskId, task.id);
// Simulate historical records with conflicting standards; migrating preserves scores and versions.
const legacyExp = createSimpleExperiment({ name: "Legacy" });
const legacyIds = ["Old 1", "Old 2", "Old 3"].map(alias => joinSimpleExperiment(legacyExp.manualInviteCode, alias).participantId);
for (const [index, id] of legacyIds.entries()) {
  const old = getSimpleDashboard(legacyExp.id).students.find(value => value.id === id)!;
  old.paper = { sourceId: paperId, paperTitle: "Legacy paper", gold: index === 1 ? [{ ...gold[0], cation: "Other" }] : gold };
  old.status = "submitted"; old.rows = gold;
  old.score = teacher.score; old.overrides = teacher.overrides;
  old.version = 42;
  getTeachingDb().prepare("UPDATE simple_students SET payload = ? WHERE id = ?").run(JSON.stringify(old), id);
}
const migrated = getSimpleDashboard(legacyExp.id);
assert.equal(migrated.tasks.length, 2);
assert.equal(migrated.students[0].taskId, migrated.students[2].taskId);
assert.notEqual(migrated.students[0].taskId, migrated.students[1].taskId);
assert.ok(migrated.students.every(value => value.version === 42));
for (const migratedStudent of migrated.students) {
  assert.deepEqual(migratedStudent.score, teacher.score);
  assert.deepEqual(migratedStudent.overrides, teacher.overrides);
}
closeTeachingStoreForTests();
console.log("simple store tests passed");
