import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = readFileSync(resolve(__dirname, 'App.vue'), 'utf8')
const sourceCount = (value: string) => (source.match(new RegExp(value, 'g')) || []).length
const sourceSlice = (start: string, end: string) => source.slice(source.indexOf(start), source.indexOf(end))

describe('App home shell', () => {
  it('uses one Elicit shell for home, library, and monitor', () => {
    expect(source).toContain("const elicitShellViews = ['home', 'library', 'admin']")
    expect(source).toContain("const chromeHiddenViews = ['home', 'library', 'admin']")
    expect(source).toContain('elicitShellViews.includes(currentView)')
    expect(source).toContain('isElicitItemLocked')
    expect(source).toContain('item.locked && !canAccessAdmin')
    expect(source).toContain('/ioniclink.png')
    expect(source).toContain("{ label: 'Home', icon: Clock3, view: 'home', section: 'today' }")
    expect(source).toContain("{ label: 'Extract', icon: Upload, modal: 'upload' }")
    expect(source).toContain("{ label: 'Database', icon: Database, modal: 'database' }")
    expect(source).toContain('Library')
    expect(source).toContain('Monitor')
    expect(source).toContain("{ label: 'Monitor', icon: Activity, view: 'admin', section: 'runtime' }")
    expect(source).toContain("{ label: 'Extraction workflow', icon: BookOpen, active: true, locked: false }")
    expect(source).toContain("{ label: 'Research agent', icon: LayoutGrid, active: false, locked: false }")
    expect(source.indexOf("{ label: 'Extract', icon: Upload, modal: 'upload' }")).toBeLessThan(source.indexOf("{ label: 'Library', icon: BookOpen"))
    expect(source.indexOf("{ label: 'Database', icon: Database, modal: 'database' }")).toBeLessThan(source.indexOf("{ label: 'Library', icon: BookOpen"))
    expect(source).toContain('openElicitTopNavItem')
    expect(source).toContain('v-else-if="currentView === \'library\'"')
    expect(source).toContain('<AdminPage')
    expect(source).toContain("{ label: 'Extract data', icon: Upload, modal: 'upload', locked: false }")
    expect(source).not.toContain("{ label: 'Alerts', icon: Bell, view: 'review', section: 'inbox' }")
  })

  it('opens the database tool as a table modal from the Elicit tools', () => {
    expect(source).toContain('DatabaseToolModal')
    expect(source).toContain("modal: 'database'")
    expect(source).toContain('openElicitTool')
    expect(source).toContain('databaseToolOpen')
    expect(source).toContain('databaseToolFocus')
    expect(source).toContain('databaseToolFocus.value = null')
    expect(source).toContain('function openLibraryExtractionDatabase')
    expect(source).toContain('@open-database="openLibraryExtractionDatabase"')
    expect(source).toContain("dataset: payload?.dataset === 'diffusion' ? 'diffusion' : 'tribology'")
    expect(source).toContain('key="database-tool-global-v2"')
    expect(source).toContain('openPdfUploadResultsInDatabase')
    expect(source).toContain('selectedFileId.value = target.id')
    expect(source).toContain('explorerDoi.value = target.doi || \'\'')
    expect(source).toContain('databaseToolFocus.value = {')
    expect(source).toContain('fileId: target.id')
    expect(source).toContain('dataset: pdfUploadDatabaseFocusDataset(target)')
    expect(source).toContain('const focusTarget = pdfUploadDatabaseFocusTarget(target)')
    expect(source).toContain('recordId: focusTarget.recordId')
    expect(source).toContain('entityType: focusTarget.entityType')
    expect(source).toContain(':focus-dataset="databaseToolFocus?.dataset || null"')
    expect(source).toContain(':selected-file-id="selectedFileId"')
    expect(source).toContain(':explorer-doi="explorerDoi"')
    expect(source).toContain(':focus-file-id="databaseToolFocus?.fileId || null"')
    expect(source).toContain(':focus-doi="databaseToolFocus?.doi || \'\'"')
    expect(source).toContain(':focus-record-id="databaseToolFocus?.recordId || null"')
    expect(source).toContain(':focus-entity-type="databaseToolFocus?.entityType || null"')
    expect(source).not.toContain(':selected-file-id="null"')
    expect(source).not.toContain(':explorer-doi="\'\'"')
  })

  it('opens completed PDF upload extraction directly in Database instead of the results preview', () => {
    const startExtractionSource = sourceSlice('async function startPdfUploadExtraction()', 'function compactAuthorLine')

    expect(source).toContain('async function openCompletedPdfUploadItemsInDatabase')
    expect(startExtractionSource).toContain('await openCompletedPdfUploadItemsInDatabase(completedItems)')
    expect(startExtractionSource).not.toContain("pdfUploadModalStep.value = 'results'")
    expect(source).toContain('pdfUploadModalOpen.value = false')
    expect(source).toContain('databaseToolOpen.value = true')
  })

  it('routes database evidence clicks into the source grounding overlay', () => {
    expect(source).toContain("mode?: 'training-blockers' | 'grounding' | null")
    expect(source).toContain('SourceGroundingView')
    expect(source).toContain('sourceGroundingOpen')
    expect(source).toContain("if (payload?.mode === 'grounding')")
    expect(source).toContain('openSourceGroundingTarget')
    expect(source).not.toContain('ReviewPage')
  })

  it('submits uploaded text extractions in parallel and treats transient status errors as retryable', () => {
    expect(source).toContain('submitPdfUploadExtractionJobs')
    expect(source).toContain('trackPdfUploadExtractionRuns')
    expect(source).toContain('Promise.allSettled(selected.map')
    expect(source).toContain("const PDF_UPLOAD_EXTRACTION_PROFILE: ExtractionProfile = 'auto'")
    expect(source).toContain("updatePdfUploadExtractionItem(paper.id, { status: 'extracting'")
    expect(source).toContain('cancelPdfUploadExtraction')
    expect(source).toContain('cancelExtraction(String(item.id), extractorType)')
    expect(source).toContain('pdfUploadCancelResultSucceeded')
    expect(source).toContain('pdfUploadCancelResultStatus')
    expect(source).toContain('pdfUploadCancelTerminalReleaseStatuses')
    expect(source).toContain("['completed', 'no_data', 'failed', 'error', 'cancelled']")
    expect(source).toContain('cancelFailedCount')
    expect(source).toContain('PDF_UPLOAD_CANCEL_TIMEOUT_MS')
    expect(source).toContain("status: 'timeout'")
    expect(source).toContain('Stop request timed out locally')
    expect(source).toContain('Stop request failed on')
    expect(source).toContain('Stopping took too long')
    expect(source).toContain('pdfUploadExtractionAbortRequested')
    expect(source).toContain('Stop extraction')
    expect(source).toContain('Continue in background')
    expect(source).toContain('Stop and upload new PDF')
    expect(source).toContain('stopPdfUploadExtractionAndUploadNew')
    expect(source).toContain('resetPdfUploadForFreshUpload')
    expect(source).toContain('pdfUploadExtractionRunToken')
    expect(source).toContain('nextPdfUploadExtractionRunToken')
    expect(source).toContain('isCurrentPdfUploadExtractionRun')
    expect(source).toContain('if (!isCurrentPdfUploadExtractionRun(runToken)) return')
    expect(source).toContain('await trackPdfUploadExtractionRuns(uncachedSelections, runToken)')
    expect(source).toContain('if (pdfUploadExtracting.value || pdfUploadExtractionItems.value.length > 0)')
    expect(source).toContain('pdfUploadRecoverableExtractionItems')
    expect(source).toContain('retryPdfUploadRecoverableExtraction')
    expect(source).toContain('Retry fresh run')
    expect(source).toContain('changePdfUploadExtractionType')
    expect(source).not.toContain('Change extraction type')
    expect(source).toContain('uploadAnotherPdfAfterExtraction')
    expect(source).toContain('Upload another PDF')
    expect(source).toContain('pdfUploadRecoverableSummaryLabel')
    expect(source).toContain('need retry or a new upload')
    expect(source).toContain('markStalledPdfUploadExtractionItems')
    expect(source).toContain('cancelStalledPdfUploadExtractionItems')
    expect(source).toContain('PDF_UPLOAD_STALLED_HEARTBEAT_MS')
    expect(source).toContain('extractionRunActivitySignature')
    expect(source).toContain('await cancelStalledPdfUploadExtractionItems(stalledSelected)')
    expect(source).toContain('Background worker stopped sending progress updates')
    expect(source).toContain('refreshActivePdfUploadServerRuns')
    expect(source).toContain("['no_data', 'failed', 'cancelled'].includes(item.status)")
    expect(source).toContain('Status check delayed, retrying')
    expect(source).toContain('isRetryablePdfUploadRunMessage')
    expect(source).toContain('Previous extraction run stalled')
    expect(source).toContain('Fresh extraction run is being queued')
    expect(source).toContain('pdfUploadRunReviewableCount')
    expect(source).toContain('summary?.diffusion_artifacts?.reviewable_count')
    expect(source).toContain("preset === 'diffusion'")
    expect(source).toContain("if (normalizedStage.startsWith('stage_c.fast_text_start')) return 34")
    expect(source).toContain("if (normalizedStage.startsWith('stage_c.fast_text_done')) return 76")
    expect(source).toContain("if (normalizedStage.startsWith('stage_b.chunk') && chunkIndex > 0 && chunkTotal > 0)")
    expect(source).toContain('pdfUploadExtractionLatestMessage(active)')
    expect(source).toContain('Latest: ${latestMessage}')
    expect(source).toContain("no_data: 'status.no_data'")
    expect(source).not.toContain("no_data: 'status.completed'")
    expect(source).toContain("const initialHasNoReviewableData = initialRecords === 0 && (initialStatus === 'no_data' || initialStatus === 'completed')")
    expect(source).toContain("status: initialHasNoReviewableData ? 'no_data' : 'completed'")
    expect(source).toContain('Math.max(weakCandidateCount, candidateCount)')
    expect(source).toContain("status: records > 0 ? 'completed' : 'no_data'")
    expect(source).toContain('pdfUploadEvidenceShouldSuppressBareEvidence')
    expect(source).toContain('isBareMatchedNumber && (!quoteText || isBareQuoteNumber)')
    expect(source).toMatch(/if \(\['no_data', 'completed'\]\.includes\(normalizedStatus\) && !pdfUploadRunHasReviewableData\(run\)\)[\s\S]*summary\?\.no_data_reason/)
    expect(source).toContain(":role=\"item.status === 'completed' && item.records > 0 ? 'button' : undefined\"")
    expect(source).not.toContain('const result = await waitForPdfUploadExtractionRun')
  })

  it('keeps PDF upload progress and failed files visible without duplicating successful uploads', () => {
    expect(source).toContain('pdfUploadFileKey(file)')
    expect(source).toContain('pdfUploadUploadProgress')
    expect(source).toContain('pdfUploadUploadErrors')
    expect(source).toContain('pdfUploadHasQueuedFiles')
    expect(source).toContain('if (pdfUploadHasQueuedFiles.value)')
    expect(source).toContain('Upload queued PDFs before continuing, or remove them.')
    expect(source).toContain(':disabled="pdfUploadUploading || !pdfUploadCanContinueFromUpload"')
    expect(source).toContain("uploadFile(file, 'tribology',")
    expect(source).toContain('updatePdfUploadUploadProgress(file, progress)')
    expect(source).toContain('pdfUploadUploadErrorMessage(error)')
    expect(source).toContain('failedFileKeys.add(fileKey)')
    expect(source).toContain('queuedPdfUploadFiles.value = queuedPdfUploadFiles.value.filter((file) => failedFileKeys.has(pdfUploadFileKey(file)))')
    expect(source).toContain('Failed:')
    expect(source).toContain('Upload progress')
  })

  it('keeps the upload modal open when continuing without uploaded PDFs', () => {
    expect(source).toContain('pdfUploadCanContinueFromUpload')
    expect(source).toContain("if (!pdfUploadCanContinueFromUpload.value)")
    expect(source).toContain("pdfUploadStatusMessage.value = 'Add PDFs before continuing.'")
    expect(source).toContain(':disabled="pdfUploadUploading || !pdfUploadCanContinueFromUpload"')
  })

  it('loads cached uploaded literature and forces a fresh extraction for uncached papers', () => {
    expect(source).toContain('type UploadedPdfPaper')
    expect(source).toContain('cachedRecordCount')
    expect(source).toContain('cachedExtractorType')
    expect(source).toContain('cachedExtractor === selectedExtractor')
    expect(source).toContain('isCachedPdfUploadPaper')
    expect(source).toContain('const cachedSelections = selected.filter(isCachedPdfUploadPaper)')
    expect(source).toContain('const uncachedSelections = selected.filter((paper) => !isCachedPdfUploadPaper(paper))')
    expect(source).toContain('buildPdfUploadExtractionItems(selected, pdfUploadExtractionItems.value')
    expect(source).toContain('extractData(String(paper.id), true')
    expect(source).not.toContain('extractData(String(paper.id), false')
  })

  it('hydrates diffusion upload results from the literature details endpoint', () => {
    expect(source).toContain("presetForPdfUploadedPaper(paper) === 'diffusion'")
    expect(source).toContain('const details = await getLiteratureDetails(Number(paper.id))')
    expect(source).toContain('details.diffusionData')
    expect(source).toContain('getLatestExtractionRun(Number(paper.id), \'diffusion\')')
    expect(source).toContain('getExtractionRunCandidates(latestRun.run_id')
    expect(source).toContain('normalizeExtractionRunCandidate(item, \'diffusion\')')
    expect(source).toContain('normalizeReviewRecord(row)')
    expect(source).toContain('getData(String(paper.id)) as TribologyData[]')
  })

  it('does not infer unsupported conductivity extraction or send unsupported jobs as NoData', () => {
    expect(source).not.toContain("return 'conductivity'")
    expect(source).toContain('disabled?: boolean')
    expect(source).toContain(":disabled=\"Boolean(option.disabled)\"")
    expect(source).toContain('pdfUploadSelectionHasUnsupportedPreset')
    expect(source).toContain("status: 'failed'")
    expect(source).toContain('Choose Tribology or Diffusion')
  })

  it('slides the Elicit sidebar away when leaving home for library', () => {
    expect(source).toContain('<Transition name="elicit-sidebar-slide">')
    expect(source).toContain('v-if="currentView === \'home\'"')
    expect(source).toContain('elicit-sidebar-slide-leave-active')
    expect(source).toContain('transform: translateX(-100%);')
  })

  it('shows extraction review publish controls in the upload results modal', () => {
    expect(sourceCount('Publish ready records')).toBe(1)
    expect(source).toContain('Confirm')
    expect(source).toContain('Flag')
    expect(source).toContain('Review status')
    expect(source).toContain('approveReviewCandidate')
    expect(source).toContain('publishLiteratureToGroupLibrary')
    expect(source).toContain('publishReadyPdfUploadRecords')
    expect(source).toContain('approveReviewRecord')
    expect(source).toContain('approveDiffusionReviewRecord')
    expect(source).toContain("target.entityType === 'record'")
    expect(source).toContain('approveReviewRecord(target.entityId)')
    expect(source).toContain('approveDiffusionReviewRecord(target.entityId)')
    expect(source).toContain('confirmRecordFieldEvidence')
    expect(source).toContain('confirmCandidateFieldEvidence')
    expect(source).toContain('flagRecordFieldEvidence')
    expect(source).toContain('flagCandidateFieldEvidence')
    expect(source).toContain('confirmDiffusionCandidateFieldEvidence')
    expect(source).toContain('confirmDiffusionRecordFieldEvidence')
    expect(source).toContain('flagDiffusionCandidateFieldEvidence')
    expect(source).toContain('flagDiffusionRecordFieldEvidence')
    expect(source).toContain('pdfUploadFieldEvidenceEntityType')
    expect(source).toContain('pdfUploadReviewTargetId')
    expect(source).toContain('row.entity_id ?? row.entityId ?? row.id')
    expect(source).toContain('pdfUploadPublishedReviewTargetKeys')
    expect(source).toContain('row.promoted_record_id = response.promoted_record_id ?? response.promotedRecordId ?? row.promoted_record_id')
    expect(source).toContain('markPdfUploadReviewTargetPublished(target)')
    expect(source).toContain('reviewPublishTargetKey(target)')
    expect(source).toContain("? confirmRecordFieldEvidence(targetId, fieldKey)")
    expect(source).toContain("? flagRecordFieldEvidence(targetId, fieldKey)")
    expect(source).toContain('pdfUploadEvidenceContextualHighlights')
    expect(source).toContain('const fallbackHighlight = isMetricField ? pdfUploadResultMetric(row) : value')
    expect(source).toContain('Publish')
    expect(source).toContain('Review')
    expect(source).not.toContain('Relevant quotes')
    expect(source).toContain('Boolean(pdfUploadReviewActionPending)')
    expect(source).not.toContain('@click="closePdfUploadModal"\n                    >\n                      Done')
  })

  it('keeps upload preview evidence split by real field instead of mixing composite cells', () => {
    expect(source).toContain('type PdfUploadEvidenceSlide')
    expect(source).toContain('pdfUploadEvidenceSlideIndex')
    expect(source).toContain('pdfUploadEvidenceSlidesForField')
    expect(source).toContain('pdfUploadEvidenceSemanticKey')
    expect(source).toContain("material_name: 'substrate_material'")
    expect(source).toContain("normal_load: 'load'")
    expect(source).toContain('pdfUploadEvidenceSlideHasContent')
    expect(source).toContain('pdfUploadBestEvidenceSlidesBySemanticKey')
    expect(source).toContain('activePdfUploadEvidenceSlide')
    expect(source).toContain('activePdfUploadEvidenceActionFieldKey')
    expect(source).toContain('movePdfUploadEvidenceSlide')
    expect(source).toContain('activePdfUploadEvidenceSlideCount')
    expect(source).toContain('activePdfUploadEvidenceSlideIndexLabel')
    expect(source).toContain('activePdfUploadEvidenceValue')
    expect(source).toContain('getPdfBboxPreview')
    expect(source).toContain('hydratePdfUploadEvidencePreviews')
    expect(source).toContain('pdfUploadEvidenceShouldRenderPdfPreview')
    expect(source).toContain('activePdfUploadEvidenceImageSrc()')
    expect(source).toContain('Highlighted PDF evidence')
    expect(source).toContain('fieldKeys: [fieldKey]')
    expect(source).toContain('if (!pdfUploadEvidenceSlideHasContent(slide)) continue')
    expect(source).toContain('return Boolean(slide.quotes.length || pdfUploadEvidenceSlideHasReliableLocator(slide))')
    expect(source).not.toContain('return Boolean(pdfUploadResultValue(slide.value) || slide.quotes.length)')
    expect(source).toContain('seenSemanticKeys')
    expect(source).toContain('activePdfUploadEvidenceActionFieldKey()')
    expect(source).toContain('aria-label="Previous upload evidence"')
    expect(source).toContain('aria-label="Next upload evidence"')
    expect(source).toContain('No field-level quote was stored for this value.')
  })

  it('does not show isolated numeric evidence for upload preview roughness or derived speed', () => {
    expect(source).toContain('pdfUploadEvidenceShouldSuppressBareEvidence')
    expect(source).toContain("fieldKey?.includes('roughness')")
    expect(source).toContain("groundingMode === 'derived'")
    expect(source).toContain('pdfUploadEvidenceHasDerivedScanContext')
    expect(source).toContain('fieldKey: key')
    expect(source).toContain('pdfUploadEvidenceHasReliableLocator')
    expect(source).toContain('if (!pdfUploadEvidenceSlideHasReliableLocator(slide)) return false')
    expect(source).toContain('if (pdfUploadEvidenceShouldSuppressBareEvidence(fieldKey, quote, matchedText, groundingMode)) return false')
    expect(source).not.toContain('pdfUploadEvidenceQuoteFromText(matchedText, matchedText)')
  })

  it('surfaces backend validation details when publishing ready records fails', () => {
    expect(source).toContain('pdfUploadReviewActionErrorMessage(error: unknown)')
    expect(source).toContain('data?.detail')
    expect(source).toContain('Candidate cannot be approved')
    expect(source).toContain('database sync failed')
  })

  it('still syncs successfully approved extraction rows into the database when some ready rows fail', () => {
    expect(source).toContain('if (publishedCount > 0) {')
    expect(source).toContain('await syncPublishedPdfUploadRecordsToDatabase()')
    expect(source).toContain('const publishIssueMessage = [...failures, ...skipped].join(\'; \')')
    expect(source).toContain('Published ${publishedCount} of ${readyRows.length} ready records and synced the database.')
    expect(source).toContain('Published ${publishedCount} of ${readyRows.length} approved records, but database sync failed:')
  })
})
