import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = readFileSync(resolve(__dirname, 'App.vue'), 'utf8')

describe('PDF upload reading-report flow', () => {
  it('changes the extract modal from the first upload screen', () => {
    expect(source).toContain("const pdfUploadStepLabels = ['Add papers', 'Read', 'Review']")
    expect(source).toContain("const pdfUploadModalTitle = computed(() => 'Extract papers')")
    expect(source).toContain('Upload PDFs. IonicLink reads first, extracts later.')
    expect(source).toContain('Drop PDFs here or click to browse.')
    expect(source).not.toContain('1. Reply')
    expect(source).not.toContain('Normal LLM-style paper response.')
    expect(source).not.toContain('Old extraction stays hidden.')
  })

  it('starts with the LLM reading report instead of legacy extraction', () => {
    expect(source).toContain('@click="startPdfUploadReadingReports"')
    expect(source).toContain('Read with LLM')
    expect(source).not.toContain('Ready to read with LLM')
    expect(source).toContain('<ReadingReportPanel')
    expect(source).toContain('@click="startPdfUploadExtraction"')
    expect(source).not.toContain('What should IonicLink read for?')
    expect(source).not.toContain('Report-first workflow')
    expect(source).not.toContain('Candidate rows and deep extraction stay manual.')
  })

  it('polls the report endpoint after starting a background report job', () => {
    expect(source).toContain('async function pollPdfUploadReadingReport')
    expect(source).toContain('await startReadingReport(paper.id, extractorType, force)')
    expect(source).toContain('await getReadingReport(paper.id, extractorType)')
    expect(source).toContain("report.status === 'running'")
  })

  it('uses a minimal report-first completion screen', () => {
    expect(source).toContain('const pdfUploadReadingReportDone = computed')
    expect(source).toContain('v-if="pdfUploadReadingReportDone"')
    expect(source).toContain('<span>Done</span>')
    expect(source).toContain(':reader="true"')
    expect(source).toContain(':editable="true"')
    expect(source).toContain('save-label="Save to Library"')
    expect(source).toContain('@save="savePdfUploadReadingReport"')
    expect(source).toContain('await updateReadingReport')
    expect(source).toContain('@click="generatePdfUploadCandidateDraft"')
    expect(source).toContain('function pdfUploadCandidateDraftMessage')
    expect(source).toContain("return `Draft candidate created. Fix core fields: ${missingLabels.join(', ')}.`")
    expect(source).toContain('const message = pdfUploadCandidateDraftMessage(result, candidateCount, alreadyPromoted)')
    expect(source).toContain('const officialRecordCount = Number(result.official_record_count || 0)')
    expect(source).toContain('records: alreadyPromoted ? Math.max(target.records, officialRecordCount) : candidateCount')
    expect(source).toContain("result.status === 'already_promoted'")
    expect(source).toContain('Official records already exist in Library.')
    expect(source).toContain('candidatePreview')
    expect(source).toContain('Cleaning preview')
    expect(source).toContain('Core {{ candidatePreviewCoreReady(livePdfUploadCandidatePreview) }}/{{ candidatePreviewCoreTotal(livePdfUploadCandidatePreview) }} required')
    expect(source).toContain('candidatePreview.core_summary')
    expect(source).toContain('candidatePreviewMissingCoreLabels')
    expect(source).toContain('Missing core')
    expect(source).toContain('v-for="label in candidatePreviewMissingCoreLabels(livePdfUploadCandidatePreview)"')
    expect(source).toContain('function candidatePreviewCanPromote')
    expect(source).toContain('function candidatePreviewReviewButtonLabel')
    expect(source).toContain('function candidatePreviewRawEntryCount')
    expect(source).toContain("candidatePreviewCanPromote(livePdfUploadCandidatePreview) ? 'Ready for Database review.' : 'Review missing core fields before approval.'")
    expect(source).toContain("candidatePreviewReviewButtonLabel(livePdfUploadCandidatePreview)")
    expect(source).toContain('Optional {{ candidatePreviewReadyCount(livePdfUploadCandidatePreview.extended_fields) }} captured')
    expect(source).toContain('Flexible {{ candidatePreviewRawEntryCount(livePdfUploadCandidatePreview) }} saved')
    expect(source).not.toContain('Extended {{ candidatePreviewReadyCount(livePdfUploadCandidatePreview.extended_fields) }}/{{ candidatePreviewTotalCount(livePdfUploadCandidatePreview.extended_fields) }}')
    expect(source).not.toContain('Draft candidates are ready for Database review.')
    expect(source).not.toContain("`${candidateCount} draft candidate${candidateCount === 1 ? '' : 's'} ready for review.`")
    expect(source).not.toContain('Raw evidence saved')
    expect(source).toContain('Clean data')
    expect(source).toContain('Fix core fields')
    expect(source).not.toContain('>\\n                    Review\\n                  </button>')
    expect(source).toContain('@click="startPdfUploadExtraction"')
    expect(source).toContain('@click="closePdfUploadModal"')
  })

  it('blocks candidate generation while the visible report has unsaved edits', () => {
    expect(source).toContain('const pdfUploadReadingReportEditing = ref(false)')
    expect(source).toContain('@editing-change="pdfUploadReadingReportEditing = $event"')
    expect(source).toContain(':disabled="pdfUploadCandidateDrafting || pdfUploadReadingReportEditing"')
    expect(source).toContain(':disabled="pdfUploadReadingReportEditing"')
    expect(source).toContain('Save report first')
    expect(source).toContain('pdfUploadReadingReportEditing.value = false')
  })

  it('clears stale candidate preview when an edited report is saved', () => {
    expect(source).toContain('const reportChanged = markdown.trim() !==')
    expect(source).toContain('candidateIds: []')
    expect(source).toContain('candidatePreview: null')
    expect(source).toContain('Report saved to Library. Generate candidates again from the edited report.')
    expect(source).toContain('Report saved to Library.')
  })

  it('keeps the in-progress reading screen compact', () => {
    expect(source).toContain('Reading with LLM')
    expect(source).toContain('pdfUploadJournalYearLine(livePdfUploadExtractionItem)')
    expect(source).toContain('Show diagnostics')
    expect(source).toContain('pdfUploadRawOutputOpen')
    expect(source).not.toContain('The LLM is still reading this paper...')
    expect(source).not.toContain('LLM READING REPORT')
  })

  it('uses journal and year as the parsed metadata subtitle for uploaded papers', () => {
    expect(source).toContain('function pdfUploadJournalYearLine')
    expect(source).toContain('return `${journal} (${year})`')
    expect(source).toContain("const journalLabel = journal || 'Journal pending'")
    expect(source).toContain("const yearLabel = year || 'Year pending'")
    expect(source).toContain('return `${journalLabel} (${yearLabel})`')
    expect(source).toContain('{{ pdfUploadJournalYearLine(paper) }}')
    expect(source).toContain('livePdfUploadExtractionItem ? pdfUploadJournalYearLine(livePdfUploadExtractionItem) :')
    expect(source).not.toContain('compactAuthorLine(paper.authors)')
    expect(source).not.toContain('compactAuthorLine(livePdfUploadExtractionItem.authors)')
    expect(source).not.toContain('if (journal) return journal')
    expect(source).not.toContain("return 'Journal pending'")
  })

  it('keeps background batch reading visible after the modal is closed', () => {
    expect(source).toContain('const pdfUploadBackgroundRunVisible = computed')
    expect(source).toContain('pdfUploadBackgroundRunPinned')
    expect(source).toContain('const pdfUploadBackgroundRunExpanded = ref(false)')
    expect(source).toContain('function reopenPdfUploadBackgroundRun')
    expect(source).toContain('aria-label="Background PDF reading status"')
    expect(source).toContain('aria-label="Toggle background run details"')
    expect(source).toContain(':aria-expanded="pdfUploadBackgroundRunExpanded ? \'true\' : \'false\'"')
    expect(source).toContain('v-if="pdfUploadBackgroundRunExpanded"')
    expect(source).toContain('aria-label="Background paper progress"')
    expect(source).toContain('v-for="item in pdfUploadExtractionItems"')
    expect(source).toContain('pdfUploadBatchRunSummary')
    expect(source).toContain('Reading queue')
    expect(source).toContain('@click="cancelPdfUploadExtraction"')
    expect(source).toContain('@click="openPdfUploadResultsInDatabase()"')
    expect(source).toContain('@click="retryPdfUploadRecoverableExtraction"')
    expect(source).toContain('Back to run')
  })

  it('keeps polling when reading report submission returns an uncertain gateway error', () => {
    expect(source).toContain('function isPdfUploadTransientReadingSubmissionError')
    expect(source).toContain('await pollPdfUploadReadingReport(paper, extractorType, runToken)')
    expect(source).toContain('Submission status unclear. Checking the background reading job...')
    expect(source).toContain('Reading report may still be running. Status check will continue...')
  })
})
